### ISSUE TITLE
從bookdown網站下架了？

### ISSUE THREAD

**Issue by personlin** [yijutseng/DataAnalyticsWithRBook#1]
原本在[bookdown](https://bookdown.org/)網站可以看到這本書的，怎麼現在消失了？

**Comment by yijutseng** [comment]
剛剛到[bookdown的GitHub page](https://github.com/rstudio/bookdown)留言了，希望他們可以把這本書加回，謝謝告知!

**Comment by yijutseng** [comment]
https://bookdown.org/home/archive/
