### ISSUE TITLE
Rfacebook

### ISSUE THREAD

**Issue by setegonz** [yijutseng/DataAnalyticsWithRBook#2]
Do you know if your explanation for the use of the Rfacebook packages works after facebook API recent changes? I saw that you upload a youtube video but since I don't understand your language it was impossible for me to know if it still works.

**Comment by yijutseng** [comment]
The package does not work after Facebook API changes. According to the package [repository](https://github.com/pablobarbera/Rfacebook), all functions of the package now require a working app that has undergone App Review.
